name: Feature-based Branching and Deployment

on:
  push:
    branches: [feature]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sample-image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy to Local Machine
        run: |
          docker stop my-container || true
          docker rm my-container || true
          docker run -d -p 8000:8000 --name my-container sample-image
